[build]
  base = "."
  publish = "build"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Functions configuration
[functions]
  directory = "netlify/functions"

# Redirect rules for API routes
# This ensures API routes go to our serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# Fallback for SPA routing - serve React app for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Cache CSV files
[[headers]]
  for = "/example_csv/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
